CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL  AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

 create table users_groups (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

alter table if exists users 
add column group_id bigint;

alter table if exists users 
add constraint FK3m0f6w0i4rvvjpmmufh5oit97 
foreign key (group_id) 
references users_groups;